/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.

## What is this?

This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

We've covered everything from Pokémon to Berry Flavors.

## Where do I start?

We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.

This API will always be publicly available and will never require any extensive setup process to consume.

Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
    
 * OpenAPI spec version: 2.7.0
 */
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemGender } from './evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemGender';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemHeldItem } from './evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemHeldItem';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemItem } from './evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemItem';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemKnownMove } from './evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemKnownMove';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemKnownMoveType } from './evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemKnownMoveType';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemLocation } from './evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemLocation';
import type { EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemTrigger } from './evolutionChainDetailChainEvolvesToItemEvolutionDetailsItemTrigger';

export type EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItem = {
  /** @nullable */
  gender: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemGender;
  /** @nullable */
  held_item: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemHeldItem;
  /** @nullable */
  item: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemItem;
  /** @nullable */
  known_move: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemKnownMove;
  /** @nullable */
  known_move_type: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemKnownMoveType;
  /** @nullable */
  location: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemLocation;
  /** @nullable */
  min_affection: number | null;
  /** @nullable */
  min_beauty: number | null;
  /** @nullable */
  min_happiness: number | null;
  /** @nullable */
  min_level: number | null;
  /** @nullable */
  needs_overworld_rain: boolean | null;
  /** @nullable */
  party_species: string | null;
  /** @nullable */
  party_type: string | null;
  /** @nullable */
  relative_physical_stats: string | null;
  time_of_day: string;
  /** @nullable */
  trade_species: string | null;
  trigger: EvolutionChainDetailChainEvolvesToItemEvolutionDetailsItemTrigger;
  turn_upside_down: boolean;
};
