/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.

## What is this?

This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

We've covered everything from Pokémon to Berry Flavors.

## Where do I start?

We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.

This API will always be publicly available and will never require any extensive setup process to consume.

Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
    
 * OpenAPI spec version: 2.7.0
 */
import type { AbilitySummary } from "./abilitySummary";
import type { RegionSummary } from "./regionSummary";
import type { MoveSummary } from "./moveSummary";
import type { GenerationName } from "./generationName";
import type { PokemonSpeciesSummary } from "./pokemonSpeciesSummary";
import type { TypeSummary } from "./typeSummary";
import type { VersionGroupSummary } from "./versionGroupSummary";

export interface GenerationDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  readonly abilities: readonly AbilitySummary[];
  main_region: RegionSummary;
  readonly moves: readonly MoveSummary[];
  readonly names: readonly GenerationName[];
  readonly pokemon_species: readonly PokemonSpeciesSummary[];
  readonly types: readonly TypeSummary[];
  readonly version_groups: readonly VersionGroupSummary[];
}
