/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.

## What is this?

This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

We've covered everything from Pokémon to Berry Flavors.

## Where do I start?

We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.

This API will always be publicly available and will never require any extensive setup process to consume.

Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
    
 * OpenAPI spec version: 2.7.0
 */
import type { MoveDetailAccuracy } from "./moveDetailAccuracy";
import type { MoveDetailPp } from "./moveDetailPp";
import type { MoveDetailPriority } from "./moveDetailPriority";
import type { MoveDetailPower } from "./moveDetailPower";
import type { MoveDetailContestCombos } from "./moveDetailContestCombos";
import type { ContestTypeSummary } from "./contestTypeSummary";
import type { ContestEffectSummary } from "./contestEffectSummary";
import type { MoveDamageClassSummary } from "./moveDamageClassSummary";
import type { MoveDetailEffectEntriesItem } from "./moveDetailEffectEntriesItem";
import type { MoveDetailEffectChangesItem } from "./moveDetailEffectChangesItem";
import type { GenerationSummary } from "./generationSummary";
import type { MoveMeta } from "./moveMeta";
import type { MoveName } from "./moveName";
import type { MoveChange } from "./moveChange";
import type { MoveDetailStatChangesItem } from "./moveDetailStatChangesItem";
import type { SuperContestEffectSummary } from "./superContestEffectSummary";
import type { MoveTargetSummary } from "./moveTargetSummary";
import type { TypeSummary } from "./typeSummary";
import type { MoveDetailMachinesItem } from "./moveDetailMachinesItem";
import type { MoveFlavorText } from "./moveFlavorText";
import type { MoveDetailLearnedByPokemonItem } from "./moveDetailLearnedByPokemonItem";

export interface MoveDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  accuracy?: MoveDetailAccuracy;
  effect_chance: number;
  pp?: MoveDetailPp;
  priority?: MoveDetailPriority;
  power?: MoveDetailPower;
  readonly contest_combos: MoveDetailContestCombos;
  contest_type: ContestTypeSummary;
  contest_effect: ContestEffectSummary;
  damage_class: MoveDamageClassSummary;
  readonly effect_entries: readonly MoveDetailEffectEntriesItem[];
  readonly effect_changes: readonly MoveDetailEffectChangesItem[];
  generation: GenerationSummary;
  readonly meta: MoveMeta;
  readonly names: readonly MoveName[];
  readonly past_values: readonly MoveChange[];
  readonly stat_changes: readonly MoveDetailStatChangesItem[];
  super_contest_effect: SuperContestEffectSummary;
  target: MoveTargetSummary;
  type: TypeSummary;
  readonly machines: readonly MoveDetailMachinesItem[];
  readonly flavor_text_entries: readonly MoveFlavorText[];
  readonly learned_by_pokemon: readonly MoveDetailLearnedByPokemonItem[];
}
