/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.

## What is this?

This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

We've covered everything from Pokémon to Berry Flavors.

## Where do I start?

We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.

This API will always be publicly available and will never require any extensive setup process to consume.

Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
    
 * OpenAPI spec version: 2.7.0
 */
import type { MoveMetaAilmentSummary } from './moveMetaAilmentSummary';
import type { MoveMetaCategorySummary } from './moveMetaCategorySummary';
import type { MoveMetaMinHits } from './moveMetaMinHits';
import type { MoveMetaMaxHits } from './moveMetaMaxHits';
import type { MoveMetaMinTurns } from './moveMetaMinTurns';
import type { MoveMetaMaxTurns } from './moveMetaMaxTurns';
import type { MoveMetaDrain } from './moveMetaDrain';
import type { MoveMetaHealing } from './moveMetaHealing';
import type { MoveMetaCritRate } from './moveMetaCritRate';
import type { MoveMetaAilmentChance } from './moveMetaAilmentChance';
import type { MoveMetaFlinchChance } from './moveMetaFlinchChance';
import type { MoveMetaStatChance } from './moveMetaStatChance';

export interface MoveMeta {
  ailment: MoveMetaAilmentSummary;
  category: MoveMetaCategorySummary;
  min_hits?: MoveMetaMinHits;
  max_hits?: MoveMetaMaxHits;
  min_turns?: MoveMetaMinTurns;
  max_turns?: MoveMetaMaxTurns;
  drain?: MoveMetaDrain;
  healing?: MoveMetaHealing;
  crit_rate?: MoveMetaCritRate;
  ailment_chance?: MoveMetaAilmentChance;
  flinch_chance?: MoveMetaFlinchChance;
  stat_chance?: MoveMetaStatChance;
}
