/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.

## What is this?

This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

We've covered everything from Pokémon to Berry Flavors.

## Where do I start?

We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.

This API will always be publicly available and will never require any extensive setup process to consume.

Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
    
 * OpenAPI spec version: 2.7.0
 */
import type { StatSummary } from './statSummary';
import type { BerryFlavorSummary } from './berryFlavorSummary';
import type { BerrySummary } from './berrySummary';
import type { NatureDetailPokeathlonStatChangesItem } from './natureDetailPokeathlonStatChangesItem';
import type { NatureBattleStylePreference } from './natureBattleStylePreference';
import type { NatureName } from './natureName';

export interface NatureDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  decreased_stat: StatSummary;
  increased_stat: StatSummary;
  likes_flavor: BerryFlavorSummary;
  hates_flavor: BerryFlavorSummary;
  readonly berries: readonly BerrySummary[];
  readonly pokeathlon_stat_changes: readonly NatureDetailPokeathlonStatChangesItem[];
  readonly move_battle_style_preferences: readonly NatureBattleStylePreference[];
  readonly names: readonly NatureName[];
}
