/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.

## What is this?

This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

We've covered everything from Pokémon to Berry Flavors.

## Where do I start?

We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.

This API will always be publicly available and will never require any extensive setup process to consume.

Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
    
 * OpenAPI spec version: 2.7.0
 */
import type { PokemonFormDetailOrder } from "./pokemonFormDetailOrder";
import type { PokemonFormDetailFormOrder } from "./pokemonFormDetailFormOrder";
import type { PokemonSummary } from "./pokemonSummary";
import type { PokemonFormDetailSprites } from "./pokemonFormDetailSprites";
import type { VersionGroupSummary } from "./versionGroupSummary";
import type { PokemonFormDetailFormNamesItem } from "./pokemonFormDetailFormNamesItem";
import type { PokemonFormDetailNamesItem } from "./pokemonFormDetailNamesItem";
import type { PokemonFormDetailTypesItem } from "./pokemonFormDetailTypesItem";

export interface PokemonFormDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  order?: PokemonFormDetailOrder;
  form_order?: PokemonFormDetailFormOrder;
  is_default?: boolean;
  is_battle_only?: boolean;
  is_mega?: boolean;
  /** @maxLength 30 */
  form_name: string;
  pokemon: PokemonSummary;
  readonly sprites: PokemonFormDetailSprites;
  version_group: VersionGroupSummary;
  readonly form_names: readonly PokemonFormDetailFormNamesItem[];
  readonly names: readonly PokemonFormDetailNamesItem[];
  readonly types: readonly PokemonFormDetailTypesItem[];
}
