/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * PokéAPI
 * All the Pokémon data you'll ever need in one place, easily accessible through a modern free open-source RESTful API.

## What is this?

This is a full RESTful API linked to an extensive database detailing everything about the Pokémon main game series.

We've covered everything from Pokémon to Berry Flavors.

## Where do I start?

We have awesome [documentation](https://pokeapi.co/docs/v2) on how to use this API. It takes minutes to get started.

This API will always be publicly available and will never require any extensive setup process to consume.

Created by [**Paul Hallett**](https://github.com/phalt) and other [**PokéAPI contributors***](https://github.com/PokeAPI/pokeapi#contributing) around the world. Pokémon and Pokémon character names are trademarks of Nintendo.
    
 * OpenAPI spec version: 2.7.0
 */
import type { PokemonSpeciesDetailOrder } from './pokemonSpeciesDetailOrder';
import type { PokemonSpeciesDetailGenderRate } from './pokemonSpeciesDetailGenderRate';
import type { PokemonSpeciesDetailCaptureRate } from './pokemonSpeciesDetailCaptureRate';
import type { PokemonSpeciesDetailBaseHappiness } from './pokemonSpeciesDetailBaseHappiness';
import type { PokemonSpeciesDetailHatchCounter } from './pokemonSpeciesDetailHatchCounter';
import type { GrowthRateSummary } from './growthRateSummary';
import type { PokemonDexEntry } from './pokemonDexEntry';
import type { PokemonSpeciesDetailEggGroupsItem } from './pokemonSpeciesDetailEggGroupsItem';
import type { PokemonColorSummary } from './pokemonColorSummary';
import type { PokemonShapeSummary } from './pokemonShapeSummary';
import type { PokemonSpeciesSummary } from './pokemonSpeciesSummary';
import type { EvolutionChainSummary } from './evolutionChainSummary';
import type { PokemonHabitatSummary } from './pokemonHabitatSummary';
import type { GenerationSummary } from './generationSummary';
import type { PokemonSpeciesDetailNamesItem } from './pokemonSpeciesDetailNamesItem';
import type { PokemonSpeciesDetailPalParkEncountersItem } from './pokemonSpeciesDetailPalParkEncountersItem';
import type { PokemonSpeciesDescription } from './pokemonSpeciesDescription';
import type { PokemonSpeciesFlavorText } from './pokemonSpeciesFlavorText';
import type { PokemonSpeciesDetailGeneraItem } from './pokemonSpeciesDetailGeneraItem';
import type { PokemonSpeciesDetailVarietiesItem } from './pokemonSpeciesDetailVarietiesItem';

export interface PokemonSpeciesDetail {
  readonly id: number;
  /** @maxLength 200 */
  name: string;
  order?: PokemonSpeciesDetailOrder;
  gender_rate?: PokemonSpeciesDetailGenderRate;
  capture_rate?: PokemonSpeciesDetailCaptureRate;
  base_happiness?: PokemonSpeciesDetailBaseHappiness;
  is_baby?: boolean;
  is_legendary?: boolean;
  is_mythical?: boolean;
  hatch_counter?: PokemonSpeciesDetailHatchCounter;
  has_gender_differences?: boolean;
  forms_switchable?: boolean;
  growth_rate: GrowthRateSummary;
  readonly pokedex_numbers: readonly PokemonDexEntry[];
  readonly egg_groups: readonly PokemonSpeciesDetailEggGroupsItem[];
  color: PokemonColorSummary;
  shape: PokemonShapeSummary;
  evolves_from_species: PokemonSpeciesSummary;
  evolution_chain: EvolutionChainSummary;
  habitat: PokemonHabitatSummary;
  generation: GenerationSummary;
  readonly names: readonly PokemonSpeciesDetailNamesItem[];
  readonly pal_park_encounters: readonly PokemonSpeciesDetailPalParkEncountersItem[];
  readonly form_descriptions: readonly PokemonSpeciesDescription[];
  readonly flavor_text_entries: readonly PokemonSpeciesFlavorText[];
  readonly genera: readonly PokemonSpeciesDetailGeneraItem[];
  readonly varieties: readonly PokemonSpeciesDetailVarietiesItem[];
}
