/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PokemonIdImport } from './routes/$pokemonId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PokemonIdRoute = PokemonIdImport.update({
  id: '/$pokemonId',
  path: '/$pokemonId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$pokemonId': {
      id: '/$pokemonId'
      path: '/$pokemonId'
      fullPath: '/$pokemonId'
      preLoaderRoute: typeof PokemonIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pokemonId': typeof PokemonIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pokemonId': typeof PokemonIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$pokemonId': typeof PokemonIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$pokemonId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$pokemonId'
  id: '__root__' | '/' | '/$pokemonId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokemonIdRoute: typeof PokemonIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokemonIdRoute: PokemonIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$pokemonId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$pokemonId": {
      "filePath": "$pokemonId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
